// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlmtirdvtmctupyccxxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbXRpcmR2dG1jdHVweWNjeHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDQyMzcsImV4cCI6MjA3MTEyMDIzN30.dn0Au0lKUuTY5QDZb6dqwDG8lvgOARMEsvdZXFOf2eU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});